### PR TITLE
ENH: Update extension metadata

### PR DESCRIPTION
**Pull request by jcfr**
Consolidate extension metadata based on the corresponding s4ext file organized
in the ExtensionsIndex repository.

### CODE REVIEW

**Comment by jcfr** [comment]
Please, could this be reviewed & merged :pray:

**Comment by jcfr** [comment]
Email sent on June 12th 2024 to @pieper with @lassoan in cc:

```
Subject: Help to merge https://github.com/SlicerFab/SlicerFab/pull/15

Hi Steve,

When you have a chance, we would appreciate your help to merge the following pull request:

  ENH: Update extension metadata
  https://github.com/SlicerFab/SlicerFab/pull/15

Changes are trivial as they only include updates to the extension metadata.

Thanks
J-Christophe
```

**Review by lassoan — APPROVED** [review]
Looks good to me, but I cannot merge, as I don't have write access.

**Comment by pieper** [comment]
Thanks @jcfr and @lassoan 👍

**Pull request merged**
